global:
    scrape_interval: 15s
    external_labels:
        monitor: "activemq"

scrape_configs:
    - job_name: "activemq"
      scrape_interval: 5s
      metrics_path: /metrics
      static_configs:
          - targets: ["activemq:8162"]
