version: "2"
services:
  alfresco:
    image: quay.io/alfresco/alfresco-content-repository:7.4.0.1
    mem_limit: 3g
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco 
        -Delasticsearch.createIndexIfNotExists=true
        -Dindex.subsystem.name=elasticsearch
        -Delasticsearch.host=elasticsearch
        -Delasticsearch.indexName=alfresco
        -Dshare.host=127.0.0.1
        -Dshare.port=8080 
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Ddeployment.method=DOCKER_COMPOSE
        -Dtransform.service.enabled=true
        -Dtransform.service.url=http://transform-router:8095
        -Dsfs.url=http://shared-file-store:8099/ 
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Dcsrf.filter.enabled=false
        -Ddsync.service.uris=http://localhost:9090/alfresco 
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
  postgres:
    image: postgres:14.4
    mem_limit: 512m
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"
  transform-router:
    image: quay.io/alfresco/alfresco-transform-router:2.0.0
    mem_limit: 512m
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      ACTIVEMQ_URL: "nio://activemq:61616"
      CORE_AIO_URL: "http://transform-core-aio:8090"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - "8095:8095"
  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:4.0.0
    mem_limit: 2g
    restart: on-failure
    environment:
      JAVA_OPTS: >-
          -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
          -Dserver.tomcat.threads.max=4
          -Dserver.tomcat.threads.min=1
      ACTIVEMQ_URL: "nio://activemq:61616"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - "8090:8090"
  shared-file-store:
    image: quay.io/alfresco/alfresco-shared-file-store:2.0.0
    mem_limit: 512m
    environment:
      JAVA_OPTS: >-
          -XX:MinRAMPercentage=50 
          -XX:MaxRAMPercentage=80
      scheduler.content.age.millis: 86400000
      scheduler.cleanup.interval: 86400000
    ports:
      - "8099:8099"
    volumes:
      - shared-file-store-volume:/tmp/Alfresco/sfs
  elasticsearch:
    image: opensearchproject/opensearch:1.3.2
    mem_limit: 2g
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: opensearchproject/opensearch-dashboards:1.3.2
    mem_limit: 1g
    environment:
      - 'OPENSEARCH_HOSTS=["http://elasticsearch:9200"]'
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  live-indexing:
    image: quay.io/alfresco/alfresco-elasticsearch-live-indexing:3.3.0
    mem_limit: 1g
    depends_on:
      - elasticsearch
      - alfresco
    environment:
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
      SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616
      ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_BASEURL: http://transform-core-aio:8090/transform/config
      ALFRESCO_SHAREDFILESTORE_BASEURL: http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file/
  reindexing:
    mem_limit: 512m
    build:
      context: ./reindexing
    depends_on:
      - elasticsearch
      - alfresco
    environment:
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
      SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/alfresco
      ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_BASEURL: http://transform-core-aio:8090/transform/config
      ALFRESCO_REINDEX_PREFIXES: file:///opt/reindex.prefixes-file.json
    volumes:
      - ./reindexing/reindex.prefixes-file.json:/opt/reindex.prefixes-file.json      
  activemq:
    image: alfresco/alfresco-activemq:5.17.1-jre11-rockylinux8
    mem_limit: 2g
    environment:
      ACTIVEMQ_OPTS: >-
          -javaagent:/opt/activemq/jmx_prometheus_javaagent-0.19.0.jar=8162:/opt/activemq/jmx_config.yaml
      ACTIVEMQ_SUNJMX_START: >-
          -Dcom.sun.management.jmxremote
          -Dcom.sun.management.jmxremote.authenticate=false
          -Dcom.sun.management.jmxremote.ssl=false
          -Dcom.sun.management.jmxremote.port=1099
          -Dcom.sun.management.jmxremote.rmi.port=1099
          -Djava.rmi.server.hostname=localhost
          -Dcom.sun.management.jmxremote.host=0.0.0.0
          -Dcom.sun.management.jmxremote.local.only=false
    ports:
      - "61616:61616"
      - "8161:8161"
      - "8162:8162"
      - "1099:1099"
    volumes:
      - ./activemq/jmx_prometheus_javaagent-0.19.0.jar:/opt/activemq/jmx_prometheus_javaagent-0.19.0.jar
      - ./activemq/jmx_config.yaml:/opt/activemq/jmx_config.yaml
      - ./activemq/jolokia-access.xml:/opt/activemq/conf/jolokia-access.xml
  prometheus:
    image: prom/prometheus
    mem_limit: 512m
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana-ui:
    image: grafana/grafana:6.3.7
    mem_limit: 512m
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana-datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./grafana/grafana-activemq.yml:/etc/grafana/provisioning/dashboards/activemq.yml
      - ./grafana/grafana-dashboard.json:/var/lib/grafana/dashboards/grafana-dashboard.json
  share:
    image: quay.io/alfresco/alfresco-share:7.4.0.1
    mem_limit: 512m
    environment:
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http
  digital-workspace:
    image: quay.io/alfresco/alfresco-digital-workspace:4.0.0
    mem_limit: 256m
    environment:
      APP_CONFIG_AUTH_TYPE: "BASIC"
      APP_CONFIG_PROVIDER: "ECM"
      BASE_PATH: ./
      APP_BASE_SHARE_URL: "http://localhost:8080/workspace/#/preview/s"
  proxy:
    image: alfresco/alfresco-acs-nginx:3.4.2
    mem_limit: 256m
    depends_on:
      - alfresco 
      - digital-workspace  
    environment:     
      - DISABLE_CONTROL_CENTER=true  
      - USE_SSL=false
    ports:
      - "8080:8080"
    links: 
      - digital-workspace  
      - alfresco 
      - share 
  sync-service:
    image: quay.io/alfresco/service-sync:3.10.0
    mem_limit: 512m
    environment:
      JAVA_OPTS: >-
        -Dsql.db.driver=org.postgresql.Driver
        -Dsql.db.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsql.db.username=alfresco
        -Dsql.db.password=alfresco
        -Dmessaging.broker.host=activemq
        -Drepo.hostname=alfresco
        -Drepo.port=8080
        -Ddw.server.applicationConnectors[0].type=http
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
    ports:
      - "9090:9090"
volumes:
  shared-file-store-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
