{
 "title": "ActiveMQ",
 "tags": [ "telegraf" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad",
     "legendFormat": "ProcessCpuLoad"
    },
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad",
     "legendFormat": "SystemCpuLoad"
    }
   ]
  },
  {
   "title": "Java Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_max",
     "legendFormat": "HeapMemoryUsage_max"
    },
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used",
     "legendFormat": "HeapMemoryUsage_used"
    }
   ]
  },
  {
   "title": "Total Consumer / Producer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_TotalConsumerCount",
     "legendFormat": "TotalConsumerCount"
    },
    {
     "expr": "org_apache_activemq_Broker_TotalProducerCount",
     "legendFormat": "TotalProducerCount"
    }
   ]
  },
  {
   "title": "Total Dequeue / Enqueue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_TotalDequeueCount",
     "legendFormat": "TotalDequeueCount"
    },
    {
     "expr": "org_apache_activemq_Broker_TotalEnqueueCount",
     "legendFormat": "TotalEnqueueCount"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Pool Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "java_lang_G1_Eden_Space_Usage_max",
     "legendFormat": "MAX"
    },
    {
     "expr": "java_lang_G1_Eden_Space_Usage_used",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory Pool PeakUsage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "java_lang_G1_Eden_Space_PeakUsage_max",
     "legendFormat": "MAX"
    },
    {
     "expr": "java_lang_G1_Eden_Space_PeakUsage_used",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Broker Store",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_StorePercentUsage",
     "legendFormat": "StorePercentUsage"
    }
   ]
  },
  {
   "title": "Broker Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 26 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_activemq_Broker_MemoryPercentUsage)",
     "legendFormat": "MemoryPercentUsage"
    }
   ]
  },
  {
   "title": "Broker Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_TempPercentUsage",
     "legendFormat": "TempPercentUsage"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Queues sizes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_activemq_Broker_QueueSize)",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Queues Consumer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_TotalConsumerCount",
     "legendFormat": "consumer"
    }
   ]
  },
  {
   "title": "Queues Dequeue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_activemq_Broker_DequeueCount)",
     "legendFormat": "dequeue"
    }
   ]
  },
  {
   "title": "Queues Enqueue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_TotalEnqueueCount",
     "legendFormat": "enqueue"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true
  },
  {
   "title": "Topic alfresco.repo.event2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_EnqueueCounter{destinationName=\"alfresco.repo.event2\"}",
     "legendFormat": "EnqueueCounter"
    },
    {
     "expr": "org_apache_activemq_Broker_DequeueCounter{destinationName=\"alfresco.repo.event2\"}",
     "legendFormat": "DequeueCounter"
    }
   ]
  }
 ]
}